// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: ss_base.proto

package config

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type S2SBaseMsgId int32

const (
	S2SBaseMsgId_s2s_base_min_msg_id              S2SBaseMsgId = 0
	S2SBaseMsgId_s2s_server_session_veriry_req_id S2SBaseMsgId = 1
	S2SBaseMsgId_s2s_server_session_veriry_ack_id S2SBaseMsgId = 2
	S2SBaseMsgId_s2s_server_session_ping_id       S2SBaseMsgId = 3
	S2SBaseMsgId_s2s_server_session_pong_id       S2SBaseMsgId = 4
	S2SBaseMsgId_s2s_client_session_ping_id       S2SBaseMsgId = 5
	S2SBaseMsgId_s2s_client_session_pong_id       S2SBaseMsgId = 6
	S2SBaseMsgId_service_discovery_req_id         S2SBaseMsgId = 7
	S2SBaseMsgId_service_discovery_ack_id         S2SBaseMsgId = 8
	S2SBaseMsgId_s2s_base_max_msg_id              S2SBaseMsgId = 299
)

// Enum value maps for S2SBaseMsgId.
var (
	S2SBaseMsgId_name = map[int32]string{
		0:   "s2s_base_min_msg_id",
		1:   "s2s_server_session_veriry_req_id",
		2:   "s2s_server_session_veriry_ack_id",
		3:   "s2s_server_session_ping_id",
		4:   "s2s_server_session_pong_id",
		5:   "s2s_client_session_ping_id",
		6:   "s2s_client_session_pong_id",
		7:   "service_discovery_req_id",
		8:   "service_discovery_ack_id",
		299: "s2s_base_max_msg_id",
	}
	S2SBaseMsgId_value = map[string]int32{
		"s2s_base_min_msg_id":              0,
		"s2s_server_session_veriry_req_id": 1,
		"s2s_server_session_veriry_ack_id": 2,
		"s2s_server_session_ping_id":       3,
		"s2s_server_session_pong_id":       4,
		"s2s_client_session_ping_id":       5,
		"s2s_client_session_pong_id":       6,
		"service_discovery_req_id":         7,
		"service_discovery_ack_id":         8,
		"s2s_base_max_msg_id":              299,
	}
)

func (x S2SBaseMsgId) Enum() *S2SBaseMsgId {
	p := new(S2SBaseMsgId)
	*p = x
	return p
}

func (x S2SBaseMsgId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (S2SBaseMsgId) Descriptor() protoreflect.EnumDescriptor {
	return file_ss_base_proto_enumTypes[0].Descriptor()
}

func (S2SBaseMsgId) Type() protoreflect.EnumType {
	return &file_ss_base_proto_enumTypes[0]
}

func (x S2SBaseMsgId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use S2SBaseMsgId.Descriptor instead.
func (S2SBaseMsgId) EnumDescriptor() ([]byte, []int) {
	return file_ss_base_proto_rawDescGZIP(), []int{0}
}

type S2SServerSessionVeriryReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerId      uint64 `protobuf:"varint,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ServerType    uint32 `protobuf:"varint,2,opt,name=server_type,json=serverType,proto3" json:"server_type,omitempty"`
	ServerTypeStr string `protobuf:"bytes,3,opt,name=server_type_str,json=serverTypeStr,proto3" json:"server_type_str,omitempty"`
	Ip            string `protobuf:"bytes,4,opt,name=ip,proto3" json:"ip,omitempty"`
	Token         string `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *S2SServerSessionVeriryReq) Reset() {
	*x = S2SServerSessionVeriryReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ss_base_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2SServerSessionVeriryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2SServerSessionVeriryReq) ProtoMessage() {}

func (x *S2SServerSessionVeriryReq) ProtoReflect() protoreflect.Message {
	mi := &file_ss_base_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2SServerSessionVeriryReq.ProtoReflect.Descriptor instead.
func (*S2SServerSessionVeriryReq) Descriptor() ([]byte, []int) {
	return file_ss_base_proto_rawDescGZIP(), []int{0}
}

func (x *S2SServerSessionVeriryReq) GetServerId() uint64 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *S2SServerSessionVeriryReq) GetServerType() uint32 {
	if x != nil {
		return x.ServerType
	}
	return 0
}

func (x *S2SServerSessionVeriryReq) GetServerTypeStr() string {
	if x != nil {
		return x.ServerTypeStr
	}
	return ""
}

func (x *S2SServerSessionVeriryReq) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *S2SServerSessionVeriryReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type S2SServerSessionVeriryAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *S2SServerSessionVeriryAck) Reset() {
	*x = S2SServerSessionVeriryAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ss_base_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2SServerSessionVeriryAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2SServerSessionVeriryAck) ProtoMessage() {}

func (x *S2SServerSessionVeriryAck) ProtoReflect() protoreflect.Message {
	mi := &file_ss_base_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2SServerSessionVeriryAck.ProtoReflect.Descriptor instead.
func (*S2SServerSessionVeriryAck) Descriptor() ([]byte, []int) {
	return file_ss_base_proto_rawDescGZIP(), []int{1}
}

type S2SServerSessionPing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *S2SServerSessionPing) Reset() {
	*x = S2SServerSessionPing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ss_base_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2SServerSessionPing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2SServerSessionPing) ProtoMessage() {}

func (x *S2SServerSessionPing) ProtoReflect() protoreflect.Message {
	mi := &file_ss_base_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2SServerSessionPing.ProtoReflect.Descriptor instead.
func (*S2SServerSessionPing) Descriptor() ([]byte, []int) {
	return file_ss_base_proto_rawDescGZIP(), []int{2}
}

type S2SServerSessionPong struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *S2SServerSessionPong) Reset() {
	*x = S2SServerSessionPong{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ss_base_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2SServerSessionPong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2SServerSessionPong) ProtoMessage() {}

func (x *S2SServerSessionPong) ProtoReflect() protoreflect.Message {
	mi := &file_ss_base_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2SServerSessionPong.ProtoReflect.Descriptor instead.
func (*S2SServerSessionPong) Descriptor() ([]byte, []int) {
	return file_ss_base_proto_rawDescGZIP(), []int{3}
}

type S2SClientSessionPing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *S2SClientSessionPing) Reset() {
	*x = S2SClientSessionPing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ss_base_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2SClientSessionPing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2SClientSessionPing) ProtoMessage() {}

func (x *S2SClientSessionPing) ProtoReflect() protoreflect.Message {
	mi := &file_ss_base_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2SClientSessionPing.ProtoReflect.Descriptor instead.
func (*S2SClientSessionPing) Descriptor() ([]byte, []int) {
	return file_ss_base_proto_rawDescGZIP(), []int{4}
}

type S2SClientSessionPong struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *S2SClientSessionPong) Reset() {
	*x = S2SClientSessionPong{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ss_base_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2SClientSessionPong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2SClientSessionPong) ProtoMessage() {}

func (x *S2SClientSessionPong) ProtoReflect() protoreflect.Message {
	mi := &file_ss_base_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2SClientSessionPong.ProtoReflect.Descriptor instead.
func (*S2SClientSessionPong) Descriptor() ([]byte, []int) {
	return file_ss_base_proto_rawDescGZIP(), []int{5}
}

type SdConnAttr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerId      uint64 `protobuf:"varint,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ServerType    uint32 `protobuf:"varint,2,opt,name=server_type,json=serverType,proto3" json:"server_type,omitempty"`
	ServerTypeStr string `protobuf:"bytes,3,opt,name=server_type_str,json=serverTypeStr,proto3" json:"server_type_str,omitempty"`
	Inter         string `protobuf:"bytes,4,opt,name=inter,proto3" json:"inter,omitempty"`
	Outer         string `protobuf:"bytes,5,opt,name=outer,proto3" json:"outer,omitempty"`
	Token         string `protobuf:"bytes,6,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *SdConnAttr) Reset() {
	*x = SdConnAttr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ss_base_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SdConnAttr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SdConnAttr) ProtoMessage() {}

func (x *SdConnAttr) ProtoReflect() protoreflect.Message {
	mi := &file_ss_base_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SdConnAttr.ProtoReflect.Descriptor instead.
func (*SdConnAttr) Descriptor() ([]byte, []int) {
	return file_ss_base_proto_rawDescGZIP(), []int{6}
}

func (x *SdConnAttr) GetServerId() uint64 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *SdConnAttr) GetServerType() uint32 {
	if x != nil {
		return x.ServerType
	}
	return 0
}

func (x *SdConnAttr) GetServerTypeStr() string {
	if x != nil {
		return x.ServerTypeStr
	}
	return ""
}

func (x *SdConnAttr) GetInter() string {
	if x != nil {
		return x.Inter
	}
	return ""
}

func (x *SdConnAttr) GetOuter() string {
	if x != nil {
		return x.Outer
	}
	return ""
}

func (x *SdConnAttr) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ServiceDiscovery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerId       uint64        `protobuf:"varint,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	S2SInterListen string        `protobuf:"bytes,2,opt,name=s2s_inter_listen,json=s2sInterListen,proto3" json:"s2s_inter_listen,omitempty"`
	S2SOuterListen string        `protobuf:"bytes,3,opt,name=s2s_outer_listen,json=s2sOuterListen,proto3" json:"s2s_outer_listen,omitempty"`
	S2SHttpSurl    string        `protobuf:"bytes,4,opt,name=s2s_http_surl,json=s2sHttpSurl,proto3" json:"s2s_http_surl,omitempty"`
	S2SHttpCurl1   string        `protobuf:"bytes,5,opt,name=s2s_http_curl1,json=s2sHttpCurl1,proto3" json:"s2s_http_curl1,omitempty"`
	S2SHttpCurl2   string        `protobuf:"bytes,6,opt,name=s2s_http_curl2,json=s2sHttpCurl2,proto3" json:"s2s_http_curl2,omitempty"`
	ConnList       []*SdConnAttr `protobuf:"bytes,7,rep,name=conn_list,json=connList,proto3" json:"conn_list,omitempty"`
	C2SInterListen string        `protobuf:"bytes,8,opt,name=c2s_inter_listen,json=c2sInterListen,proto3" json:"c2s_inter_listen,omitempty"`
	C2SOuterListen string        `protobuf:"bytes,9,opt,name=c2s_outer_listen,json=c2sOuterListen,proto3" json:"c2s_outer_listen,omitempty"`
	C2SHttpsUrl    string        `protobuf:"bytes,10,opt,name=c2s_https_url,json=c2sHttpsUrl,proto3" json:"c2s_https_url,omitempty"`
	C2SHttpsCert   string        `protobuf:"bytes,11,opt,name=c2s_https_cert,json=c2sHttpsCert,proto3" json:"c2s_https_cert,omitempty"`
	C2SHttpsKey    string        `protobuf:"bytes,12,opt,name=c2s_https_key,json=c2sHttpsKey,proto3" json:"c2s_https_key,omitempty"`
	SdkTcpInter    string        `protobuf:"bytes,13,opt,name=sdk_tcp_inter,json=sdkTcpInter,proto3" json:"sdk_tcp_inter,omitempty"`
	SdkTcpOut      string        `protobuf:"bytes,14,opt,name=sdk_tcp_out,json=sdkTcpOut,proto3" json:"sdk_tcp_out,omitempty"`
	SdkHttpsUrtl   string        `protobuf:"bytes,15,opt,name=sdk_https_urtl,json=sdkHttpsUrtl,proto3" json:"sdk_https_urtl,omitempty"`
	SdkHttpsCert   string        `protobuf:"bytes,16,opt,name=sdk_https_cert,json=sdkHttpsCert,proto3" json:"sdk_https_cert,omitempty"`
	SdkHttpsKey    string        `protobuf:"bytes,17,opt,name=sdk_https_key,json=sdkHttpsKey,proto3" json:"sdk_https_key,omitempty"`
}

func (x *ServiceDiscovery) Reset() {
	*x = ServiceDiscovery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ss_base_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceDiscovery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceDiscovery) ProtoMessage() {}

func (x *ServiceDiscovery) ProtoReflect() protoreflect.Message {
	mi := &file_ss_base_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceDiscovery.ProtoReflect.Descriptor instead.
func (*ServiceDiscovery) Descriptor() ([]byte, []int) {
	return file_ss_base_proto_rawDescGZIP(), []int{7}
}

func (x *ServiceDiscovery) GetServerId() uint64 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *ServiceDiscovery) GetS2SInterListen() string {
	if x != nil {
		return x.S2SInterListen
	}
	return ""
}

func (x *ServiceDiscovery) GetS2SOuterListen() string {
	if x != nil {
		return x.S2SOuterListen
	}
	return ""
}

func (x *ServiceDiscovery) GetS2SHttpSurl() string {
	if x != nil {
		return x.S2SHttpSurl
	}
	return ""
}

func (x *ServiceDiscovery) GetS2SHttpCurl1() string {
	if x != nil {
		return x.S2SHttpCurl1
	}
	return ""
}

func (x *ServiceDiscovery) GetS2SHttpCurl2() string {
	if x != nil {
		return x.S2SHttpCurl2
	}
	return ""
}

func (x *ServiceDiscovery) GetConnList() []*SdConnAttr {
	if x != nil {
		return x.ConnList
	}
	return nil
}

func (x *ServiceDiscovery) GetC2SInterListen() string {
	if x != nil {
		return x.C2SInterListen
	}
	return ""
}

func (x *ServiceDiscovery) GetC2SOuterListen() string {
	if x != nil {
		return x.C2SOuterListen
	}
	return ""
}

func (x *ServiceDiscovery) GetC2SHttpsUrl() string {
	if x != nil {
		return x.C2SHttpsUrl
	}
	return ""
}

func (x *ServiceDiscovery) GetC2SHttpsCert() string {
	if x != nil {
		return x.C2SHttpsCert
	}
	return ""
}

func (x *ServiceDiscovery) GetC2SHttpsKey() string {
	if x != nil {
		return x.C2SHttpsKey
	}
	return ""
}

func (x *ServiceDiscovery) GetSdkTcpInter() string {
	if x != nil {
		return x.SdkTcpInter
	}
	return ""
}

func (x *ServiceDiscovery) GetSdkTcpOut() string {
	if x != nil {
		return x.SdkTcpOut
	}
	return ""
}

func (x *ServiceDiscovery) GetSdkHttpsUrtl() string {
	if x != nil {
		return x.SdkHttpsUrtl
	}
	return ""
}

func (x *ServiceDiscovery) GetSdkHttpsCert() string {
	if x != nil {
		return x.SdkHttpsCert
	}
	return ""
}

func (x *ServiceDiscovery) GetSdkHttpsKey() string {
	if x != nil {
		return x.SdkHttpsKey
	}
	return ""
}

type ServiceDiscoveryReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerId uint64 `protobuf:"varint,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Token    string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *ServiceDiscoveryReq) Reset() {
	*x = ServiceDiscoveryReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ss_base_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceDiscoveryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceDiscoveryReq) ProtoMessage() {}

func (x *ServiceDiscoveryReq) ProtoReflect() protoreflect.Message {
	mi := &file_ss_base_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceDiscoveryReq.ProtoReflect.Descriptor instead.
func (*ServiceDiscoveryReq) Descriptor() ([]byte, []int) {
	return file_ss_base_proto_rawDescGZIP(), []int{8}
}

func (x *ServiceDiscoveryReq) GetServerId() uint64 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *ServiceDiscoveryReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ServiceDiscoveryAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RebuildFlag bool              `protobuf:"varint,1,opt,name=rebuild_flag,json=rebuildFlag,proto3" json:"rebuild_flag,omitempty"`
	VerifyFlag  bool              `protobuf:"varint,2,opt,name=verify_flag,json=verifyFlag,proto3" json:"verify_flag,omitempty"`
	SdInfo      *ServiceDiscovery `protobuf:"bytes,3,opt,name=sd_info,json=sdInfo,proto3" json:"sd_info,omitempty"`
}

func (x *ServiceDiscoveryAck) Reset() {
	*x = ServiceDiscoveryAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ss_base_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceDiscoveryAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceDiscoveryAck) ProtoMessage() {}

func (x *ServiceDiscoveryAck) ProtoReflect() protoreflect.Message {
	mi := &file_ss_base_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceDiscoveryAck.ProtoReflect.Descriptor instead.
func (*ServiceDiscoveryAck) Descriptor() ([]byte, []int) {
	return file_ss_base_proto_rawDescGZIP(), []int{9}
}

func (x *ServiceDiscoveryAck) GetRebuildFlag() bool {
	if x != nil {
		return x.RebuildFlag
	}
	return false
}

func (x *ServiceDiscoveryAck) GetVerifyFlag() bool {
	if x != nil {
		return x.VerifyFlag
	}
	return false
}

func (x *ServiceDiscoveryAck) GetSdInfo() *ServiceDiscovery {
	if x != nil {
		return x.SdInfo
	}
	return nil
}

var File_ss_base_proto protoreflect.FileDescriptor

var file_ss_base_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x73, 0x73, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x02, 0x70, 0x62, 0x22, 0xab, 0x01, 0x0a, 0x1d, 0x73, 0x32, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x5f, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x76, 0x65, 0x72, 0x69, 0x72,
	0x79, 0x5f, 0x72, 0x65, 0x71, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x26, 0x0a, 0x0f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x5f, 0x73, 0x74, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x53, 0x74, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x22, 0x1f, 0x0a, 0x1d, 0x73, 0x32, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f,
	0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x76, 0x65, 0x72, 0x69, 0x72, 0x79, 0x5f, 0x61,
	0x63, 0x6b, 0x22, 0x19, 0x0a, 0x17, 0x73, 0x32, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x5f, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x70, 0x69, 0x6e, 0x67, 0x22, 0x19, 0x0a,
	0x17, 0x73, 0x32, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x5f, 0x70, 0x6f, 0x6e, 0x67, 0x22, 0x19, 0x0a, 0x17, 0x73, 0x32, 0x73, 0x5f,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x70,
	0x69, 0x6e, 0x67, 0x22, 0x19, 0x0a, 0x17, 0x73, 0x32, 0x73, 0x5f, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x5f, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x70, 0x6f, 0x6e, 0x67, 0x22, 0xb6,
	0x01, 0x0a, 0x0c, 0x73, 0x64, 0x5f, 0x63, 0x6f, 0x6e, 0x6e, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x12,
	0x1b, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x26, 0x0a,
	0x0f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x73, 0x74, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x79,
	0x70, 0x65, 0x53, 0x74, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x6f,
	0x75, 0x74, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x75, 0x74, 0x65,
	0x72, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x99, 0x05, 0x0a, 0x11, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x5f, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x12, 0x1b, 0x0a,
	0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x10, 0x73, 0x32,
	0x73, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x73, 0x32, 0x73, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x4c, 0x69,
	0x73, 0x74, 0x65, 0x6e, 0x12, 0x28, 0x0a, 0x10, 0x73, 0x32, 0x73, 0x5f, 0x6f, 0x75, 0x74, 0x65,
	0x72, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e,
	0x73, 0x32, 0x73, 0x4f, 0x75, 0x74, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x12, 0x22,
	0x0a, 0x0d, 0x73, 0x32, 0x73, 0x5f, 0x68, 0x74, 0x74, 0x70, 0x5f, 0x73, 0x75, 0x72, 0x6c, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x32, 0x73, 0x48, 0x74, 0x74, 0x70, 0x53, 0x75,
	0x72, 0x6c, 0x12, 0x24, 0x0a, 0x0e, 0x73, 0x32, 0x73, 0x5f, 0x68, 0x74, 0x74, 0x70, 0x5f, 0x63,
	0x75, 0x72, 0x6c, 0x31, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x32, 0x73, 0x48,
	0x74, 0x74, 0x70, 0x43, 0x75, 0x72, 0x6c, 0x31, 0x12, 0x24, 0x0a, 0x0e, 0x73, 0x32, 0x73, 0x5f,
	0x68, 0x74, 0x74, 0x70, 0x5f, 0x63, 0x75, 0x72, 0x6c, 0x32, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x73, 0x32, 0x73, 0x48, 0x74, 0x74, 0x70, 0x43, 0x75, 0x72, 0x6c, 0x32, 0x12, 0x2d,
	0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x6e, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x07, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x73, 0x64, 0x5f, 0x63, 0x6f, 0x6e, 0x6e, 0x5f, 0x61,
	0x74, 0x74, 0x72, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x28, 0x0a,
	0x10, 0x63, 0x32, 0x73, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x65,
	0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x32, 0x73, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x12, 0x28, 0x0a, 0x10, 0x63, 0x32, 0x73, 0x5f, 0x6f,
	0x75, 0x74, 0x65, 0x72, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0e, 0x63, 0x32, 0x73, 0x4f, 0x75, 0x74, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x65,
	0x6e, 0x12, 0x22, 0x0a, 0x0d, 0x63, 0x32, 0x73, 0x5f, 0x68, 0x74, 0x74, 0x70, 0x73, 0x5f, 0x75,
	0x72, 0x6c, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x32, 0x73, 0x48, 0x74, 0x74,
	0x70, 0x73, 0x55, 0x72, 0x6c, 0x12, 0x24, 0x0a, 0x0e, 0x63, 0x32, 0x73, 0x5f, 0x68, 0x74, 0x74,
	0x70, 0x73, 0x5f, 0x63, 0x65, 0x72, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63,
	0x32, 0x73, 0x48, 0x74, 0x74, 0x70, 0x73, 0x43, 0x65, 0x72, 0x74, 0x12, 0x22, 0x0a, 0x0d, 0x63,
	0x32, 0x73, 0x5f, 0x68, 0x74, 0x74, 0x70, 0x73, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x0c, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x63, 0x32, 0x73, 0x48, 0x74, 0x74, 0x70, 0x73, 0x4b, 0x65, 0x79, 0x12,
	0x22, 0x0a, 0x0d, 0x73, 0x64, 0x6b, 0x5f, 0x74, 0x63, 0x70, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x64, 0x6b, 0x54, 0x63, 0x70, 0x49, 0x6e,
	0x74, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0b, 0x73, 0x64, 0x6b, 0x5f, 0x74, 0x63, 0x70, 0x5f, 0x6f,
	0x75, 0x74, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x64, 0x6b, 0x54, 0x63, 0x70,
	0x4f, 0x75, 0x74, 0x12, 0x24, 0x0a, 0x0e, 0x73, 0x64, 0x6b, 0x5f, 0x68, 0x74, 0x74, 0x70, 0x73,
	0x5f, 0x75, 0x72, 0x74, 0x6c, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x64, 0x6b,
	0x48, 0x74, 0x74, 0x70, 0x73, 0x55, 0x72, 0x74, 0x6c, 0x12, 0x24, 0x0a, 0x0e, 0x73, 0x64, 0x6b,
	0x5f, 0x68, 0x74, 0x74, 0x70, 0x73, 0x5f, 0x63, 0x65, 0x72, 0x74, 0x18, 0x10, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x73, 0x64, 0x6b, 0x48, 0x74, 0x74, 0x70, 0x73, 0x43, 0x65, 0x72, 0x74, 0x12,
	0x22, 0x0a, 0x0d, 0x73, 0x64, 0x6b, 0x5f, 0x68, 0x74, 0x74, 0x70, 0x73, 0x5f, 0x6b, 0x65, 0x79,
	0x18, 0x11, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x64, 0x6b, 0x48, 0x74, 0x74, 0x70, 0x73,
	0x4b, 0x65, 0x79, 0x22, 0x4a, 0x0a, 0x15, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x64,
	0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x5f, 0x72, 0x65, 0x71, 0x12, 0x1b, 0x0a, 0x09,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22,
	0x8b, 0x01, 0x0a, 0x15, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x64, 0x69, 0x73, 0x63,
	0x6f, 0x76, 0x65, 0x72, 0x79, 0x5f, 0x61, 0x63, 0x6b, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x62,
	0x75, 0x69, 0x6c, 0x64, 0x5f, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x0b, 0x72, 0x65, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x46, 0x6c, 0x61, 0x67, 0x12, 0x1f, 0x0a, 0x0b,
	0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x5f, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0a, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x46, 0x6c, 0x61, 0x67, 0x12, 0x2e, 0x0a,
	0x07, 0x73, 0x64, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x70, 0x62, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x64, 0x69, 0x73, 0x63,
	0x6f, 0x76, 0x65, 0x72, 0x79, 0x52, 0x06, 0x73, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x2a, 0xc9, 0x02,
	0x0a, 0x0c, 0x53, 0x32, 0x53, 0x42, 0x61, 0x73, 0x65, 0x4d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x17,
	0x0a, 0x13, 0x73, 0x32, 0x73, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x6d, 0x69, 0x6e, 0x5f, 0x6d,
	0x73, 0x67, 0x5f, 0x69, 0x64, 0x10, 0x00, 0x12, 0x24, 0x0a, 0x20, 0x73, 0x32, 0x73, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x76, 0x65,
	0x72, 0x69, 0x72, 0x79, 0x5f, 0x72, 0x65, 0x71, 0x5f, 0x69, 0x64, 0x10, 0x01, 0x12, 0x24, 0x0a,
	0x20, 0x73, 0x32, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x5f, 0x76, 0x65, 0x72, 0x69, 0x72, 0x79, 0x5f, 0x61, 0x63, 0x6b, 0x5f, 0x69,
	0x64, 0x10, 0x02, 0x12, 0x1e, 0x0a, 0x1a, 0x73, 0x32, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x5f, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x70, 0x69, 0x6e, 0x67, 0x5f, 0x69,
	0x64, 0x10, 0x03, 0x12, 0x1e, 0x0a, 0x1a, 0x73, 0x32, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x5f, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x70, 0x6f, 0x6e, 0x67, 0x5f, 0x69,
	0x64, 0x10, 0x04, 0x12, 0x1e, 0x0a, 0x1a, 0x73, 0x32, 0x73, 0x5f, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x5f, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x70, 0x69, 0x6e, 0x67, 0x5f, 0x69,
	0x64, 0x10, 0x05, 0x12, 0x1e, 0x0a, 0x1a, 0x73, 0x32, 0x73, 0x5f, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x5f, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x70, 0x6f, 0x6e, 0x67, 0x5f, 0x69,
	0x64, 0x10, 0x06, 0x12, 0x1c, 0x0a, 0x18, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x64,
	0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x5f, 0x72, 0x65, 0x71, 0x5f, 0x69, 0x64, 0x10,
	0x07, 0x12, 0x1c, 0x0a, 0x18, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x64, 0x69, 0x73,
	0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x5f, 0x61, 0x63, 0x6b, 0x5f, 0x69, 0x64, 0x10, 0x08, 0x12,
	0x18, 0x0a, 0x13, 0x73, 0x32, 0x73, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x6d, 0x61, 0x78, 0x5f,
	0x6d, 0x73, 0x67, 0x5f, 0x69, 0x64, 0x10, 0xab, 0x02, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2f, 0x3b,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ss_base_proto_rawDescOnce sync.Once
	file_ss_base_proto_rawDescData = file_ss_base_proto_rawDesc
)

func file_ss_base_proto_rawDescGZIP() []byte {
	file_ss_base_proto_rawDescOnce.Do(func() {
		file_ss_base_proto_rawDescData = protoimpl.X.CompressGZIP(file_ss_base_proto_rawDescData)
	})
	return file_ss_base_proto_rawDescData
}

var file_ss_base_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ss_base_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_ss_base_proto_goTypes = []interface{}{
	(S2SBaseMsgId)(0),                 // 0: pb.S2SBaseMsgId
	(*S2SServerSessionVeriryReq)(nil), // 1: pb.s2s_server_session_veriry_req
	(*S2SServerSessionVeriryAck)(nil), // 2: pb.s2s_server_session_veriry_ack
	(*S2SServerSessionPing)(nil),      // 3: pb.s2s_server_session_ping
	(*S2SServerSessionPong)(nil),      // 4: pb.s2s_server_session_pong
	(*S2SClientSessionPing)(nil),      // 5: pb.s2s_client_session_ping
	(*S2SClientSessionPong)(nil),      // 6: pb.s2s_client_session_pong
	(*SdConnAttr)(nil),                // 7: pb.sd_conn_attr
	(*ServiceDiscovery)(nil),          // 8: pb.service_discovery
	(*ServiceDiscoveryReq)(nil),       // 9: pb.service_discovery_req
	(*ServiceDiscoveryAck)(nil),       // 10: pb.service_discovery_ack
}
var file_ss_base_proto_depIdxs = []int32{
	7, // 0: pb.service_discovery.conn_list:type_name -> pb.sd_conn_attr
	8, // 1: pb.service_discovery_ack.sd_info:type_name -> pb.service_discovery
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ss_base_proto_init() }
func file_ss_base_proto_init() {
	if File_ss_base_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ss_base_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2SServerSessionVeriryReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ss_base_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2SServerSessionVeriryAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ss_base_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2SServerSessionPing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ss_base_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2SServerSessionPong); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ss_base_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2SClientSessionPing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ss_base_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2SClientSessionPong); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ss_base_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SdConnAttr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ss_base_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceDiscovery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ss_base_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceDiscoveryReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ss_base_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceDiscoveryAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ss_base_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ss_base_proto_goTypes,
		DependencyIndexes: file_ss_base_proto_depIdxs,
		EnumInfos:         file_ss_base_proto_enumTypes,
		MessageInfos:      file_ss_base_proto_msgTypes,
	}.Build()
	File_ss_base_proto = out.File
	file_ss_base_proto_rawDesc = nil
	file_ss_base_proto_goTypes = nil
	file_ss_base_proto_depIdxs = nil
}
